try{jQuery(document).on("click",".bwp-rc-older-nav",function(){container=jQuery(this).parents(".bwp-rc-ajax-nav");var e={bwp_doing_ajax:1,bwp_rc_action:"older",bwp_rc_instance:container.find('input[name="bwp_rc_instance"]').val(),bwp_rc_paged:container.find('input[name="bwp_rc_paged"]').val(),bwp_rc_paged_limit:container.find('input[name="bwp_rc_paged_limit"]').val(),bwp_rc_paged_template:container.find('input[name="bwp_rc_paged_template"]').val()};jQuery.get(bwp_ajax_url,e,function(e){container.parents(".bwp-rc-ulist").html(e)});return false});jQuery(document).on("click",".bwp-rc-newer-nav",function(){container=jQuery(this).parents(".bwp-rc-ajax-nav");var e={bwp_doing_ajax:1,bwp_rc_action:"newer",bwp_rc_instance:container.find('input[name="bwp_rc_instance"]').val(),bwp_rc_paged:container.find('input[name="bwp_rc_paged"]').val(),bwp_rc_paged_limit:container.find('input[name="bwp_rc_paged_limit"]').val(),bwp_rc_paged_template:container.find('input[name="bwp_rc_paged_template"]').val()};jQuery.get(bwp_ajax_url,e,function(e){container.parents(".bwp-rc-ulist").html(e)});return false});}catch(e){}
try{jQuery(document).ready(function($){$(".likes li").click(function(){if(parseInt($(this).attr("data-c"))===0){var wich=$(this).attr("data-like");var post_id=parseInt($(this).attr("data-id"));var like_type=$(this).attr("data-type");$("#"+like_type+"like-"+post_id).attr("data-c",1);$("#"+like_type+"dislike-"+post_id).attr("data-c",1);var data={action:'mandegarweb_savelike2',like_type:like_type,wich:wich,post_ids:post_id};$.post(the_like_url.like_url,data,function(response)
{var x=$.parseJSON(response);$("#"+like_type+"like-"+post_id).html(x["like"]+" <i class='fa fa-thumbs-up'></i>");$("#"+like_type+"dislike-"+post_id).html(x["dislike"]+" <i class='fa fa-thumbs-down'></i>");});}})});}catch(e){}
try{var quotescollectionInstances=[];function quotescollectionRefresh(args){if(args.ajaxRefresh&&!args.autoRefresh)
jQuery("#"+args.instanceID+" .nav-next").html(quotescollectionAjax.loading);jQuery.ajax({type:"POST",url:quotescollectionAjax.ajaxUrl,data:"action=quotescollection&_ajax_nonce="+quotescollectionAjax.nonce+"&current="+args.currQuoteID+"&char_limit="+args.charLimit+"&tags="+args.tags+"&orderby="+args.orderBy,success:function(response){if(response=='-1'||!response){if(args.ajaxRefresh&&args.autoRefresh)
quotescollectionTimer(args);else if(args.ajaxRefresh&&!args.autoRefresh)
jQuery("#"+args.instanceID+" .nav-next").html('<a class=\"next-quote-link\" style=\"cursor:pointer;\" onclick=\"quotescollectionRefreshInstance(\''+args.instanceID+'\')\">'+quotescollectionAjax.nextQuote+'</a>');}
else{if(args.dynamicFetch){args.dynamicFetch=0;}
args.currQuoteID=response.quote_id;quotescollectionInstances[args.instanceID]=args;display=quotescollectionDisplayFormat(response,args);jQuery("#"+args.instanceID).hide();jQuery("#"+args.instanceID).html(display,args);jQuery("#"+args.instanceID).fadeIn('slow');if(args.ajaxRefresh&&args.autoRefresh)
quotescollectionTimer(args);}},error:function(xhr,textStatus,errorThrown){console.log(textStatus+' '+xhr.status+': '+errorThrown);if(args.ajaxRefresh&&!args.autoRefresh){jQuery("#"+args.instanceID+" .nav-next").html('<a class=\"next-quote-link\" style=\"cursor:pointer;\" onclick=\"quotescollectionRefreshInstance(\''+args.instanceID+'\')\">'+quotescollectionAjax.nextQuote+';</a>');}}});}
function quotescollectionDisplayFormat(quoteData,args){var display="";var attribution="";display+='<p>'+quoteData.quote+'</p>';if(args.showAuthor&&quoteData.author&&quoteData.author!='null'){attribution='<cite class=\"author\">'+quoteData.author+'</cite>';}
if(args.showSource&&quoteData.source&&quoteData.source!='null'){if(attribution)attribution+=', ';attribution+='<cite class=\"source title\">'+quoteData.source+'</cite>';}
if(attribution){display+=args.beforeAttribution+attribution+args.afterAttribution;}
display=args.before+display+args.after;if(args.ajaxRefresh&&!args.autoRefresh)
display+='<div class=\"navigation\"><div class=\"nav-next\"><a class=\"next-quote-link\" style=\"cursor:pointer;\" onclick=\"quotescollectionRefreshInstance(\''+args.instanceID+'\')\">'+quotescollectionAjax.nextQuote+'</a></div></div>';return display;}
function quotescollectionRefreshInstance(instanceID){quotescollectionRefresh(quotescollectionInstances[instanceID]);}
function quotescollectionTimer(args){var timeInterval=args.autoRefresh*1000;var autoRefreshMax=Number(quotescollectionAjax.autoRefreshMax);var autoRefreshCount=Number(quotescollectionAjax.autoRefreshCount);if(!quotescollectionInstances[args.instanceID])
quotescollectionInstances[args.instanceID]=args;if((autoRefreshMax==0)||(autoRefreshCount<autoRefreshMax)){setTimeout("quotescollectionRefreshInstance('"+args.instanceID+"')",timeInterval);quotescollectionAjax.autoRefreshCount=++autoRefreshCount;}};}catch(e){}
try{!function(a,b){"use strict";function c(){if(!e){e=!0;var a,c,d,f,g=-1!==navigator.appVersion.indexOf("MSIE 10"),h=!!navigator.userAgent.match(/Trident.*rv:11\./),i=b.querySelectorAll("iframe.wp-embedded-content");for(c=0;c<i.length;c++){if(d=i[c],!d.getAttribute("data-secret"))f=Math.random().toString(36).substr(2,10),d.src+="#?secret="+f,d.setAttribute("data-secret",f);if(g||h)a=d.cloneNode(!0),a.removeAttribute("security"),d.parentNode.replaceChild(a,d)}}}var d=!1,e=!1;if(b.querySelector)if(a.addEventListener)d=!0;if(a.wp=a.wp||{},!a.wp.receiveEmbedMessage)if(a.wp.receiveEmbedMessage=function(c){var d=c.data;if(d)if(d.secret||d.message||d.value)if(!/[^a-zA-Z0-9]/.test(d.secret)){var e,f,g,h,i,j=b.querySelectorAll('iframe[data-secret="'+d.secret+'"]'),k=b.querySelectorAll('blockquote[data-secret="'+d.secret+'"]');for(e=0;e<k.length;e++)k[e].style.display="none";for(e=0;e<j.length;e++)if(f=j[e],c.source===f.contentWindow){if(f.removeAttribute("style"),"height"===d.message){if(g=parseInt(d.value,10),g>1e3)g=1e3;else if(~~g<200)g=200;f.height=g}if("link"===d.message)if(h=b.createElement("a"),i=b.createElement("a"),h.href=f.getAttribute("src"),i.href=d.value,i.host===h.host)if(b.activeElement===f)a.top.location.href=d.value}else;}},d)a.addEventListener("message",a.wp.receiveEmbedMessage,!1),b.addEventListener("DOMContentLoaded",c,!1),a.addEventListener("load",c,!1)}(window,document);}catch(e){}